kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.database.name }}
  namespace: "{{ .Values.global.sepsisdemo.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ .Values.global.datacenter.storageClassName }}
  volumeMode: Filesystem